"""add inner_id

Revision ID: e76c2ca5562e
Revises: 54fee6a7ecd8
Create Date: 2023-02-28 22:29:31.595257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e76c2ca5562e"
down_revision = "54fee6a7ecd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### add innner_id column and last_sample_inner_id ###
    op.add_column(
        "task",
        sa.Column(
            "last_sample_inner_id",
            sa.Integer(),
            nullable=True,
            comment="The last inner id of sample in a task",
        ),
    )
    op.add_column(
        "task_sample",
        sa.Column(
            "inner_id", sa.Integer(), nullable=True, comment="sample id in a task"
        ),
    )
    op.create_index(
        op.f("ix_task_sample_inner_id"), "task_sample", ["inner_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_sample_inner_id"), table_name="task_sample")
    op.drop_column("task_sample", "inner_id")
    op.drop_column("task", "last_sample_inner_id")
    # ### end Alembic commands ###
